-- INFOTESS SDMS — Full Reset (single query)
-- Paste this ONE block into SQL Editor and run it

-- Kill everything
TRUNCATE notifications, message_reads, messages, receipts, payments, students, system_settings, news, users RESTART IDENTITY CASCADE;

-- USERS (passwords: admin123 / student123)
-- Passwords: admin123 / student123 (bcrypt hashes generated by Node.js bcryptjs)
INSERT INTO users (email, password_hash, role, status) VALUES
  ('admin@infotess.com',    '$2a$10$rsym/eXO9gaJUCwuN03sT.5zHOgyhxs/ViNYSXMpn8.X3eVsJpr1S', 'super_admin', 'active'),
  ('student@infotess.com',  '$2a$10$rmZWxceVmsND7FABcM6z1u/7bmVOl64ioYUVKq2jLMNcLY1y4ynGa', 'student',     'active'),
  ('ama@infotess.com',      '$2a$10$rmZWxceVmsND7FABcM6z1u/7bmVOl64ioYUVKq2jLMNcLY1y4ynGa', 'student',     'active'),
  ('john@infotess.com',     '$2a$10$rmZWxceVmsND7FABcM6z1u/7bmVOl64ioYUVKq2jLMNcLY1y4ynGa', 'student',     'active'),
  ('test2@student.com',     '$2a$10$rmZWxceVmsND7FABcM6z1u/7bmVOl64ioYUVKq2jLMNcLY1y4ynGa', 'student',     'active');

-- STUDENTS (index: 52301000XX)
INSERT INTO students (user_id, index_number, full_name, department, level, phone_number) VALUES
  (2, '5230100001', 'Ama Serwaa',   'B.Ed. Information Technology', '100', '+233244123456'),
  (4, '5230100002', 'John Mensah',  'Computer Science',            '200', '+233201122334'),
  (3, '5230100003', 'Ama Kwarteng', 'B.Ed. Information Technology', '100', '+233551234567'),
  (5, '5230100005', 'Kofi Asante',  'Computer Science',            '100', '+233279988776');

-- SYSTEM SETTINGS
INSERT INTO system_settings (setting_key, setting_value) VALUES
  ('annual_dues_amount', '200.00'),
  ('current_academic_year', '2026'),
  ('current_semester', '1'),
  ('org_member_since', '2024-09-01');

-- PAYMENTS (total GH₵ 375)
INSERT INTO payments (student_id, amount, academic_year, semester, payment_method, payment_date, receipt_number, recorded_by) VALUES
  (1, 100.00, '2026', '1', 'Cash',          '2026-03-10', 'INFO-2603-0001', 1),
  (1,  50.00, '2026', '1', 'Mobile Money',  '2026-04-02', 'INFO-2604-0002', 1),
  (3, 150.00, '2026', '1', 'Bank Transfer', '2026-03-18', 'INFO-2603-0004', 1),
  (2,  75.00, '2026', '1', 'Cash',          '2026-04-24', 'INFO-2604-0005', 1);

-- RECEIPTS
INSERT INTO receipts (payment_id, receipt_file_path, verification_hash) VALUES
  (1, 'receipt_INFO-2603-0001.html', encode(sha256(('INFO-2603-0001' || '100.00')::bytea), 'hex')),
  (2, 'receipt_INFO-2604-0002.html', encode(sha256(('INFO-2604-0002' || '50.00')::bytea), 'hex')),
  (3, 'receipt_INFO-2603-0004.html', encode(sha256(('INFO-2603-0004' || '150.00')::bytea), 'hex')),
  (4, 'receipt_INFO-2604-0005.html', encode(sha256(('INFO-2604-0005' || '75.00')::bytea), 'hex'));

-- NOTIFICATIONS
INSERT INTO notifications (user_id, title, message) VALUES
  (2, 'Welcome to INFOTESS Portal', 'Welcome to the INFOTESS student portal. Check your dashboard regularly for updates.'),
  (2, 'Dues Payment Reminder', 'Please review your dues status and complete pending payments before the deadline.');
